/* This file is autogenerated by kb-parser program.
 * If you edit this file, it might be overridden and
 * all changes may be lost. Edit the rule base instead.*/



#include "kb-init.h"



const NAME percept[24] = {
    { PERCEPT_BASE_CLOSE,          "PERCEPT_BASE_CLOSE" },
    { PERCEPT_BOT_CLOSE,           "PERCEPT_BOT_CLOSE" },
    { PERCEPT_PLAYER_CLOSE,        "PERCEPT_PLAYER_CLOSE" },
    { PERCEPT_FIRED_SPECIAL_CLOSE, "PERCEPT_FIRED_SPECIAL_CLOSE" },
    { PERCEPT_FIRED_AMMO_CLOSE,    "PERCEPT_FIRED_AMMO_CLOSE" },
    { PERCEPT_BETTER_MAIN_CLOSE,   "PERCEPT_BETTER_MAIN_CLOSE" },
    { PERCEPT_WORSE_MAIN_CLOSE,    "PERCEPT_WORSE_MAIN_CLOSE" },
    { PERCEPT_SPECIAL_CLOSE,       "PERCEPT_SPECIAL_CLOSE" },
    { PERCEPT_HIGH_ENERGY,         "PERCEPT_HIGH_ENERGY" },
    { PERCEPT_LOW_ENERGY,          "PERCEPT_LOW_ENERGY" },
    { PERCEPT_IN_BASE,             "PERCEPT_IN_BASE" },
    { PERCEPT_SLOTS_EMPTY,         "PERCEPT_SLOTS_EMPTY" },
    { PERCEPT_SLOTS_FULL,          "PERCEPT_SLOTS_FULL" },
    { PERCEPT_MAIN_IS_PREFERRED,   "PERCEPT_MAIN_IS_PREFERRED" },
    { PERCEPT_GROUND_CLOSE,        "PERCEPT_GROUND_CLOSE" },
    { PERCEPT_GROUND_HIT,          "PERCEPT_GROUND_HIT" },
    { PERCEPT_IN_WATER,            "PERCEPT_IN_WATER" },
    { PERCEPT_STOPPED,             "PERCEPT_STOPPED" },
    { PERCEPT_LOW_SPEED,           "PERCEPT_LOW_SPEED" },
    { PERCEPT_MEDIUM_SPEED,        "PERCEPT_MEDIUM_SPEED" },
    { PERCEPT_HIGH_SPEED,          "PERCEPT_HIGH_SPEED" },
    { PERCEPT_FULL_SPEED,          "PERCEPT_FULL_SPEED" },
    { PERCEPT_COLLISION_YELLOW,    "PERCEPT_COLLISION_YELLOW" },
    { PERCEPT_COLLISION_RED,       "PERCEPT_COLLISION_RED" }
};


const NAME variables_WIMPY[1] = {
    { WIMPY_ALARM, "WIMPY_ALARM" }
};

/* Initialize KB.*/
void 
initKB_WIMPY(KNOWLEDGE *kb) {

    JUMPTARGET* target;
    RULE* rule;

    logDebug( DBG_BOT|DBG_GLO|DBG_FUN, "initKB_WIMPY(%#x)", kb);

    kb->variable_names  = variables_WIMPY;
    kb->percept_names  = percept;
    kb->variable_count  = 1;
    kb->percept_count  = 24;

    /* Reserve space for world grid. */
    kb->square_size  = SHIPW >> 1;
    kb->grid_width   = (int) (levw / kb->square_size) + 1;
    kb->grid_height  = (int) (levh / kb->square_size) + 1;
    kb->grid_size    = sizeof(Uint8) * kb->grid_width * kb->grid_height;

    logDebug( DBG_BOT|DBG_GLO|DBG_DET, "levw = %d", levw);
    logDebug( DBG_BOT|DBG_GLO|DBG_DET, "levh = %d", levh);
    logDebug( DBG_BOT|DBG_GLO|DBG_DET, "kb->square_size = %d", kb->square_size);
    logDebug( DBG_BOT|DBG_GLO|DBG_DET, "kb->grid_width = %d", kb->grid_width);
    logDebug( DBG_BOT|DBG_GLO|DBG_DET, "kb->grid_height = %d", kb->grid_height);
    logDebug( DBG_BOT|DBG_GLO|DBG_DET, "kb->grid_size = %d", kb->grid_size);

    kb->grid = (Uint8*) malloc(kb->grid_size);

    memset(kb->grid, (char) SQUARE_UNKNOWN,  kb->grid_size);

    /* Set parameters. */
    kb->player_scan_range = 10000;
    kb->bot_scan_range = 10000;
    kb->item_scan_range = 2500;
    kb->ammo_scan_range = 2500;
    kb->special_scan_range = 2500;
    kb->low_energy_limit = 50;
    kb->high_energy_limit = 90;

    /* Set main weapon preference order. */
    kb->w_main_preference[W_TUHNU] = 1;
    kb->w_main_preference[W_PEAGUN] = 2;
    kb->w_main_preference[W_SLING] = 3;
    kb->w_main_preference[W_BIGPEAGUN] = 4;
    kb->w_main_preference[W_BIGSLING] = 5;
    kb->w_main_preference[W_BLASTGUN] = 6;
    kb->w_main_preference[W_MINIBLAST] = 7;
    kb->w_main_preference[W_BLASTER] = 8;
    kb->w_main_preference[W_BIGBLASTR] = 9;

    /* Rules of WIMPY knowledge base. */

    /* Jump target: 'fight' */
    target = makeJumpTarget(1);
    addJumpTarget(kb, target);

    /* Jump target: 'start' */
    target = makeJumpTarget(2);
    addJumpTarget(kb, target);

    /* Add rules for jump target 'fight' (1).*/
    target = findJumpTarget(kb, 1);

    rule = makeKBRule();
    rule->premise_positive_variables = IGNORE_ALL;
    rule->premise_positive_percepts = PERCEPT_PLAYER_CLOSE;
    rule->premise_negative_variables = IGNORE_ALL;
    rule->premise_negative_percepts = IGNORE_ALL;
    rule->conclusion_positive_variables = MODIFY_NONE;
    rule->conclusion_negative_variables = MODIFY_NONE;
    rule->cmd = CMD_NOP;
    rule->special = NULL;
    rule->conclusion_action.flags = ACTION_FIRE_MAIN;
    addKBRule(target, rule);

    /* Add rules for jump target 'start' (2).*/
    target = findJumpTarget(kb, 2);

    rule = makeKBRule();
    rule->premise_positive_variables = IGNORE_ALL;
    rule->premise_positive_percepts = IGNORE_ALL;
    rule->premise_negative_variables = IGNORE_ALL;
    rule->premise_negative_percepts = PERCEPT_HIGH_SPEED | PERCEPT_FULL_SPEED;
    rule->conclusion_positive_variables = MODIFY_NONE;
    rule->conclusion_negative_variables = MODIFY_NONE;
    rule->cmd = CMD_BREAK;
    rule->special = NULL;
    rule->conclusion_action.flags = ACTION_THRUST;
    addKBRule(target, rule);

    rule = makeKBRule();
    rule->premise_positive_variables = IGNORE_ALL;
    rule->premise_positive_percepts = PERCEPT_COLLISION_RED;
    rule->premise_negative_variables = WIMPY_ALARM;
    rule->premise_negative_percepts = IGNORE_ALL;
    rule->conclusion_positive_variables = WIMPY_ALARM;
    rule->conclusion_negative_variables = MODIFY_NONE;
    rule->cmd = CMD_NOP;
    rule->special = NULL;
    rule->conclusion_action.flags = ACTION_NOT_DEFINED;
    addKBRule(target, rule);

    rule = makeKBRule();
    rule->premise_positive_variables = IGNORE_ALL;
    rule->premise_positive_percepts = PERCEPT_COLLISION_YELLOW;
    rule->premise_negative_variables = WIMPY_ALARM;
    rule->premise_negative_percepts = IGNORE_ALL;
    rule->conclusion_positive_variables = WIMPY_ALARM;
    rule->conclusion_negative_variables = MODIFY_NONE;
    rule->cmd = CMD_NOP;
    rule->special = NULL;
    rule->conclusion_action.flags = ACTION_NOT_DEFINED;
    addKBRule(target, rule);

    rule = makeKBRule();
    rule->premise_positive_variables = IGNORE_ALL;
    rule->premise_positive_percepts = PERCEPT_GROUND_HIT;
    rule->premise_negative_variables = WIMPY_ALARM;
    rule->premise_negative_percepts = IGNORE_ALL;
    rule->conclusion_positive_variables = WIMPY_ALARM;
    rule->conclusion_negative_variables = MODIFY_NONE;
    rule->cmd = CMD_NOP;
    rule->special = NULL;
    rule->conclusion_action.flags = ACTION_NOT_DEFINED;
    addKBRule(target, rule);

    rule = makeKBRule();
    rule->premise_positive_variables = WIMPY_ALARM;
    rule->premise_positive_percepts = IGNORE_ALL;
    rule->premise_negative_variables = IGNORE_ALL;
    rule->premise_negative_percepts = PERCEPT_COLLISION_RED | PERCEPT_COLLISION_YELLOW | PERCEPT_GROUND_HIT;
    rule->conclusion_positive_variables = MODIFY_NONE;
    rule->conclusion_negative_variables = WIMPY_ALARM;
    rule->cmd = CMD_NOP;
    rule->special = NULL;
    rule->conclusion_action.flags = ACTION_NOT_DEFINED;
    addKBRule(target, rule);

    rule = makeKBRule();
    rule->premise_positive_variables = WIMPY_ALARM;
    rule->premise_positive_percepts = IGNORE_ALL;
    rule->premise_negative_variables = IGNORE_ALL;
    rule->premise_negative_percepts = IGNORE_ALL;
    rule->conclusion_positive_variables = MODIFY_NONE;
    rule->conclusion_negative_variables = MODIFY_NONE;
    rule->cmd = CMD_NOP;
    rule->special = NULL;
    rule->conclusion_action.flags = ACTION_TURN_RIGHT;
    addKBRule(target, rule);

    rule = makeKBRule();
    rule->premise_positive_variables = IGNORE_ALL;
    rule->premise_positive_percepts = PERCEPT_PLAYER_CLOSE;
    rule->premise_negative_variables = IGNORE_ALL;
    rule->premise_negative_percepts = IGNORE_ALL;
    rule->conclusion_positive_variables = MODIFY_NONE;
    rule->conclusion_negative_variables = MODIFY_NONE;
    rule->cmd = CMD_JUMP;
    rule->special = NULL;
    rule->conclusion_action.flags = ACTION_NOT_DEFINED;
    addKBRule(target, rule);
    /* Set jump target. */
    setJumpTo(kb, rule, 1);

    /* Set start rule.*/
    target = findJumpTarget(kb, 2);
    setStartRule(kb, target->rule);

    /* All done. */
}

const int kbChoiceCount = 1;

KBINFO kbChoice[1] = {
    { "WIMPY", initKB_WIMPY, variables_WIMPY }

};

