/* $Id: kb-init.h,v 1.1 2003/04/15 18:15:56 tonic Exp $
 * $Revision: 1.1 $
 */

/* This file is autogenerated by kb-parser program.
 * If you edit this file, it might be overridden and
 * all changes may be lost. Edit the rule base instead.*/



#ifndef KOPS_KB_INIT_H
#define KOPS_KB_INIT_H
#include "cannonfodder.h"

/* Start common definitions */

#define IGNORE_ALL  0x0
#define MODIFY_NONE 0x0

extern const NAME percept[];
/* End common definitions */


/* Start percept definitions. */
#define PERCEPT_BASE_CLOSE          0x0000001
#define PERCEPT_BOT_CLOSE           0x0000002
#define PERCEPT_PLAYER_CLOSE        0x0000004
#define PERCEPT_FIRED_SPECIAL_CLOSE 0x0000008
#define PERCEPT_FIRED_AMMO_CLOSE    0x0000010
#define PERCEPT_BETTER_MAIN_CLOSE   0x0000020
#define PERCEPT_WORSE_MAIN_CLOSE    0x0000040
#define PERCEPT_SPECIAL_CLOSE       0x0000080
#define PERCEPT_HIGH_ENERGY         0x0000100
#define PERCEPT_LOW_ENERGY          0x0000200
#define PERCEPT_IN_BASE             0x0000400
#define PERCEPT_SLOTS_EMPTY         0x0000800
#define PERCEPT_SLOTS_FULL          0x0001000
#define PERCEPT_MAIN_IS_PREFERRED   0x0002000
#define PERCEPT_GROUND_CLOSE        0x0004000
#define PERCEPT_GROUND_HIT          0x0008000
#define PERCEPT_IN_WATER            0x0010000
#define PERCEPT_STOPPED             0x0020000
#define PERCEPT_LOW_SPEED           0x0040000
#define PERCEPT_MEDIUM_SPEED        0x0080000
#define PERCEPT_HIGH_SPEED          0x0100000
#define PERCEPT_FULL_SPEED          0x0200000
#define PERCEPT_COLLISION_YELLOW    0x0400000
#define PERCEPT_COLLISION_RED       0x0800000

/* End percept definitions. */


/* Start variable definitions for WIMPY */
#define WIMPY_ALARM 0x0000001

/* End variable definitions for WIMPY */

extern void initKB_WIMPY(KNOWLEDGE *kb);
#endif /* !KOPS_KB_INIT_H */
