name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-latest
    steps:
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |-
          sudo apt-get update
          sudo apt-get install -qy --no-install-recommends libsdl2-dev libsdl2-mixer-dev zlib1g-dev
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |-
          brew update
          brew install sdl2 sdl2_mixer
      - uses: actions/checkout@v3
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
